Newsweek Clone page with Bootstrap
queeksm/bootstrap-project pull request #2
Opened 2019-12-04 20:54 UTC by queeksm

This is a clone of the newsweek main page made using HTML/CSS and Bootstrap

2019-12-04 21:38 UTC, pelzolga123 commented on index.html
> +          </button>
`Subscribe` should be a link.

2019-12-04 21:39 UTC, pelzolga123 requested changes
Requires changes.

2019-12-04 21:39 UTC, pelzolga123 commented
## Great  work :+1:
### Your project looks amazing! But more changes are required:
* [ ] Please check HTML markup with this [validator](https://validator.w3.org/#validate_by_upload). Now it shows  error.

* [ ] Subscribe should be a link like on original website.

* [ ] This section in Tablet version needs a little correction:
![image](https://user-images.githubusercontent.com/20416431/70181614-e518fd80-16ea-11ea-99d3-0ad970d5eb85.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/70181743-2dd0b680-16eb-11ea-9656-91b4fe9e1ad9.png)

* [ ] Mobile version needs to be more responsive
![image](https://user-images.githubusercontent.com/20416431/70182046-be0efb80-16eb-11ea-8429-64de8d80b809.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/70182156-f3b3e480-16eb-11ea-8417-ef54b1809f31.png)

* [ ] `Latest news` section needs to be responsive:
![image](https://user-images.githubusercontent.com/20416431/70182354-59a06c00-16ec-11ea-8297-243c2da619ec.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/70182476-92d8dc00-16ec-11ea-89bf-7a3aaed6bd1c.png)

* [ ] Footer needs some adjustment:
![image](https://user-images.githubusercontent.com/20416431/70182687-067ae900-16ed-11ea-9cae-195d311a4dc7.png)

* [ ] You have a lot of css in this project, but main goal is to use as many bootstrap classes as possible. Please try to reduce amount of your css code and add more bootstrap. [Link to screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png)

### Please kindly Fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2019-12-05 04:21 UTC, nikasulo approved these changes
# This is so great 👏
Please merge and see you at the top!  :rocket:

2019-12-05 05:25 UTC, merged